### PR TITLE
Nao back

### PR DESCRIPTION
**Pull request by kovalp**
Additions:
  an implementation of iterative TDDFT with local density approximation.
The code needs a DFT starting point provided by SIESTA package which is a pseudo-potential, numerical atomic orbitals based code.

I reverted the CMakeLists.txt to its original state (from master branch).

### CODE REVIEW

**Comment by sunqm** [comment]
The default CMakeLists.txt was deleted in your branch.  Please do not delete this file.

**Comment by kovalp** [comment]
I assumed you can merge in such a way, that the file remains in the dev
branch.

To delete the file providing some examples instead was the simplest
solution to manage the linking against different libraries.

Does the removal breaks some automatic procedure?

Peter

El 8 sept. 2017 7:09 PM, "Qiming Sun" <notifications@github.com> escribió:

The default CMakeLists.txt was deleted in your branch. Please do not delete
this file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sunqm/pyscf/pull/118#issuecomment-328161273>, or mute
the thread

**Comment by kovalp** [comment]
Dear Quiming and Timothy,

Thanks for the merge. What would be your preference for a next development
step concerning the iterative TDDFT/GW/BSE?

I admit I still cannot achieve reproducible runs across different python
installations. So I spent all time trying different installations instead
of adding new features or refactoring the code. Next steps in adding
features for me will be GWA which should be first realised as a
perturbative correction to dft or hf energy levels. I would like to have a
contour deformation technique employed to treat frequency dependent
 self-energy.

I will look into the available gw implementation to see whether it is
possible to have a unified implementation.

Best regards from San Sebastian,

Peter

**Comment by sunqm** [comment]
For TDDFT, I will implement the UKS-TDDFT grandients and some excited states molecular or crystal properties, and improve the stability and performance if needed.  It will happen probably next year during release 1.6 or 1.7.  Honestly, I do not have a clear plan of the GW development.  Basically, I think what is needed here is a good system or project to drive the development of TDDFT and GW.

Qiming

**Comment by kovalp** [comment]
Hello Quiming,

where the tests from the test/ directory landed?

**Comment by sunqm** [comment]
https://github.com/sunqm/pyscf/tree/dev/pyscf/nao/test

**Pull request merged**
